{% include './common.yaml' %}

assets_subdir: "dark"
background_color: "#17181d"
background_color_alt: "#1f1f27"
background_color_disabled: "#181818"
border_color: "#444444"
button_pressed: "#2d2d2d"
checkbox_check: "#ffffff"
combobox: "#1f1f27"
highlight: "{{ palette.white }}"
hscrollbar: "#666666"
hscrollbar_groove: "#111111"
item_handle: "#ffffff"
text_background_color: "#1f1f27"
text_color: "#dddddd"
text_color_alt: "#1e1e1e"
text_color_disabled: "#d0d0d0"
tab_selected: "#aaaaaa"
track_panel_background: "#17181d"
vscrollbar: "#666666"
vscrollbar_groove: "#111111"
