assets_subdir: "dark"
background_color: "#17181d"
background_color_alt: "#1f1f27"
background_color_disabled: "#181818"
border_color: "#333333"
button_pressed: "#2d2d2d"
checkbox_check: "#ffffff"
combobox: "#1f1f27"
font_size_mm: 7
hscrollbar: "#666666"
hscrollbar_groove: "#111111"
item_handle: "#ffffff"
palette:
  black: "#111111"
  purple: "#8212f2"
  white: "#cccccc"
text_background_color: "#1f1f27"
text_color: "#dddddd"
text_color_alt: "#1e1e1e"
text_color_disabled: "#d0d0d0"
tool_button_offset: 0
tab_selected: "#aaaaaa"
track_panel_background: "#17181d"
transport_button_size: 15
transport_clock_background: "#333390"
vscrollbar: "#666666"
vscrollbar_groove: "#111111"
