background_color: "#282828"
background_color_alt: "#232323"
background_color_disabled: "#181818"
border_color: "#1e1e1e"
combobox: "#999999"
hscrollbar: "#666666"
hscrollbar_groove: "#111111"
item_handle: "#ffffff"
text_background_color: "#5f5f61"
text_color: "#dddddd"
text_color_dark: "#1e1e1e"
text_color_disabled: "#d0d0d0"
tool_button_offset: 10
track_panel_background: "#292929"
transport_button_size: 40
vscrollbar: "#666666"
vscrollbar_groove: "#111111"
